// Creamos un array de objetos para almacenar los productos
const productos = [
    {
        id: 1,
        productName: "ajies",
        price: 200,
        quanty: 1,
        img: "../media/aji.png",
    },
    {
        id: 2,
        productName: "Bananas",
        price: 480,
        quanty: 1,
        img: "../media/bananas.png",
    },
    {
        id: 3,
        productName: "Berenjenas",
        price: 320,
        quanty: 1,
        img: "../media/berenjena.png",
    },
    {
        id: 4,
        productName: "Duraznos",
        price: 670,
        quanty: 1,
        img: "../media/durazno.png",
    },
    {
        id: 5,
        productName: "Ensalada de frutas",
        price: 1000,
        quanty: 1,
        img: "../media/ensalada_fruta.png",
    },
    {
        id: 6,
        productName: "Frutillas",
        price: 1500,
        quanty: 1,
        img: "../media/frutillas.png",
    },
    {
        id: 7,
        productName: "Helado con frutas",
        price: 3400,
        quanty: 1,
        img: "../media/helado_con_frutas.png",
    },
    {
        id: 8,
        productName: "Jugos",
        price: 500,
        quanty: 1,
        img: "../media/jugos.png",
    },
    {
        id: 9,
        productName: "Licuado de frutillas",
        price: 480,
        quanty: 1,
        img: "../media/licuado_frutilla.png",
    },
    {
        id: 10,
        productName: "Licuados",
        price: 450,
        quanty: 1,
        img: "../media/licuados.png",
    },
    {
        id: 11,
        productName: "Limas",
        price: 320,
        quanty: 1,
        img: "../media/lima.png",
    },
    {
        id: 12,
        productName: "Limon amarillo",
        price: 220,
        quanty: 1,
        img: "../media/limon_amarillo.png",
    },
    {
        id: 13,
        productName: "Manzanas verdes",
        price: 650,
        quanty: 1,
        img: "../media/manzana_verde.png",
    },
    {
        id: 14,
        productName: "Morrones",
        price: 300,
        quanty: 1,
        img: "../media/morrones.png",
    },
    {
        id: 15,
        productName: "piña",
        price: 1750,
        quanty: 1,
        img: "../media/piña.png",
    },
    {
        id: 16,
        productName: "Sandias",
        price: 5000,
        quanty: 1,
        img: "../media/sandia.png",
    },
    {
        id: 17,
        productName: "Tazón de ensalada de frutas",
        price: 4500,
        quanty: 1,
        img: "../media/tazon_ensalada.png",
    },
    {
        id: 1,
        productName: "Tomates",
        price: 200,
        quanty: 1,
        img: "../media/tomate.png",
    },
]